
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jun 24 19:56:29 CEST 2021
//----------------------------------------------------

package ch.richebach.srlang.parser;

/** CUP generated interface containing symbol constants. */
public interface Terminals {
  /* terminals */
  public static final int kwRoundOpen = 15;
  public static final int identifier = 24;
  public static final int kwGreater = 8;
  public static final int kwCurlyOpen = 10;
  public static final int kwEnd = 17;
  public static final int literalInteger = 2;
  public static final int literalBoolean = 3;
  public static final int kwSub = 16;
  public static final int kwLess = 7;
  public static final int kwIf = 20;
  public static final int kwAssign = 5;
  public static final int kwRoundClose = 14;
  public static final int kwElse = 18;
  public static final int EOF = 0;
  public static final int kwEqual = 6;
  public static final int kwDiv = 11;
  public static final int kwEcho = 23;
  public static final int kwAdd = 4;
  public static final int kwList = 12;
  public static final int kwLoop = 21;
  public static final int error = 1;
  public static final int kwFunction = 19;
  public static final int kwMul = 13;
  public static final int kwReturn = 22;
  public static final int kwCurlyClose = 9;
}

