
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jun 23 14:19:14 CEST 2021
//----------------------------------------------------

package ch.ffhs.srlang.skript.parser;

/** CUP generated interface containing symbol constants. */
public interface Terminals {
  /* terminals */
  public static final int kwRoundOpen = 14;
  public static final int comment = 22;
  public static final int identifier = 23;
  public static final int kwCurlyOpen = 9;
  public static final int kwEnd = 16;
  public static final int literalInteger = 3;
  public static final int literalBoolean = 2;
  public static final int kwSub = 15;
  public static final int kwIf = 19;
  public static final int kwCompare = 7;
  public static final int kwAssign = 6;
  public static final int kwRoundClose = 13;
  public static final int kwElse = 17;
  public static final int EOF = 0;
  public static final int kwDiv = 10;
  public static final int kwAdd = 5;
  public static final int kwList = 11;
  public static final int kwLoop = 20;
  public static final int error = 1;
  public static final int kwFunction = 18;
  public static final int kwMul = 12;
  public static final int kwReturn = 21;
  public static final int kwCurlyClose = 8;
  public static final int literalString = 4;
}

