
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jun 23 23:19:33 CEST 2021
//----------------------------------------------------

package ch.ffhs.srlang.skript.parser;

/** CUP generated interface containing symbol constants. */
public interface Terminals {
  /* terminals */
  public static final int kwRoundOpen = 12;
  public static final int comment = 21;
  public static final int identifier = 22;
  public static final int kwCurlyOpen = 7;
  public static final int kwEnd = 14;
  public static final int literalInteger = 2;
  public static final int kwSub = 13;
  public static final int kwIf = 17;
  public static final int kwCompare = 5;
  public static final int kwAssign = 4;
  public static final int kwRoundClose = 11;
  public static final int kwElse = 15;
  public static final int EOF = 0;
  public static final int kwDiv = 8;
  public static final int kwEcho = 20;
  public static final int kwAdd = 3;
  public static final int kwList = 9;
  public static final int kwLoop = 18;
  public static final int error = 1;
  public static final int kwFunction = 16;
  public static final int kwMul = 10;
  public static final int kwReturn = 19;
  public static final int kwCurlyClose = 6;
}

