
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jun 24 12:30:46 CEST 2021
//----------------------------------------------------

package ch.ffhs.srlang.skript.parser;

/** CUP generated interface containing symbol constants. */
public interface Terminals {
  /* terminals */
  public static final int kwRoundOpen = 13;
  public static final int identifier = 22;
  public static final int kwCurlyOpen = 8;
  public static final int kwEnd = 15;
  public static final int literalInteger = 2;
  public static final int kwSub = 14;
  public static final int kwLess = 6;
  public static final int kwIf = 18;
  public static final int kwAssign = 4;
  public static final int kwRoundClose = 12;
  public static final int kwElse = 16;
  public static final int EOF = 0;
  public static final int kwEqual = 5;
  public static final int kwDiv = 9;
  public static final int kwEcho = 21;
  public static final int kwAdd = 3;
  public static final int kwList = 10;
  public static final int kwLoop = 19;
  public static final int error = 1;
  public static final int kwFunction = 17;
  public static final int kwMul = 11;
  public static final int kwReturn = 20;
  public static final int kwCurlyClose = 7;
}

